version: '2'

services:

  x11-xpra:
    image: reto/x11-xpra
    container_name: x11-xpra
    ports:
      - "2020:20"
    volumes:
      # copy ssh public key
      - ~/.ssh/id_rsa.pub:/home/user/.ssh/authorized_keys
    
  
  firefox:
    image: dockerworxinc/fmyfirefox
    container_name: firefox
    volumes:
      # copy ssh public key
      - ~/.ssh/id_rsa.pub:/home/user/.ssh/authorized_keys
      
      
  
  
